CREATE DATABASE CALL_CENTER;
USE CALL_CENTER;

RENAME TABLE `CALLS_CENTRE` TO CALLS_CENTER;

ALTER TABLE CALLS_CENTER
RENAME COLUMN `ï»¿id` TO ID; 

-- ** Change the date Formatt ** --

UPDATE CALLS_CENTER
SET CALL_TIMESTAMP = STR_TO_DATE(CALL_TIMESTAMP, '%Y-%m-%d');

-- ** Update empty Columns with Nulls ** --

UPDATE CALLS_CENTER
SET CSAT_SCORE = NULL
WHERE CSAT_SCORE = '';

SELECT * FROM CALLS_CENTER;

-- ** Count of num of rows and columns in table **--

SELECT COUNT(*) AS NUM_OF_ROW FROM CALLS_CENTER;

SELECT COUNT(*) AS NUM_OF_COLUMN FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'CALLS_CENTER' AND TABLE_SCHEMA = 'CALL_CENTER';

-- ** Find the distinct values in each column **--

SELECT DISTINCT SENTIMENT FROM CALLS_CENTER;
SELECT DISTINCT CITY FROM CALLS_CENTER;
SELECT DISTINCT CALL_CENTER FROM CALLS_CENTER;

-- ** Find the count and Percentage from total of each distinct values in a column in call_center table ---

SELECT CITY, COUNT(*) AS COUNT, COUNT(*) * 100 / (SELECT COUNT(*) FROM CALLS_CENTER) AS PERCENTAGE
FROM CALLS_CENTER
GROUP BY CITY;

-- ** Find number of Call count of each day of the week **--

SELECT DAYNAME(CALL_TIMESTAMP) AS DAY_OF_WEEK, COUNT(*) AS CALL_COUNT
FROM CALLS_CENTER
GROUP BY DAY_OF_WEEK
ORDER BY CALL_COUNT;

-- ** Aggregate Calculations of Call Duration **--

SELECT 
	MIN(CALL_DURATION_IN_MINUTES) AS MINIMUN_CALL_DURATION, 
    MAX(CALL_DURATION_IN_MINUTES) AS MAXIMUM_CALL_DURATION,
    AVG(CALL_DURATION_IN_MINUTES) AS AVG_CALL_DURATION
FROM CALLS_CENTER;

SELECT
	MIN(CSAT_SCORE) AS MINIMUN_CSAT_SCORE,
    MAX(CSAT_SCORE) AS MAXIMUM_CSAT_SCORE,
    ROUND(AVG(CSAT_SCORE),2) AS AVG_CSAT_SCORE
FROM CALLS_CENTER
WHERE CSAT_SCORE <> 0;

SELECT RESPONSE_TIME, CALL_CENTER, COUNT(*) AS TOTAL
FROM CALLS_CENTER
GROUP BY RESPONSE_TIME, CALL_CENTER
ORDER BY TOTAL DESC;

SELECT
	DATE(CALL_TIMESTAMP) AS CALL_DAYS,
    MAX(CALL_DURATION_IN_MINUTES) AS MAX_CALL_DURATION 
FROM CALLS_CENTER
GROUP BY CALL_DAYS
ORDER BY MAX_CALL_DURATION;